### ISSUE TITLE
Web application starting error caused by missing property

### ISSUE THREAD

**Issue by alexctinpirtea** [cross-logis/netbuilder#7]
### This is an error related to a missing property in the base deploy.properties configuration file that is preventing the web application from starting properly.

<details><summary>View full stacktrace for more information</summary>
<p>

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'exFormatEditorBuilder': Injection of autowired dependencies failed; nested exception is 
> java.lang.IllegalArgumentException: Could not resolve placeholder 'cross.configuration.exportData.maxNumberOfThreads' in value "${cross.configuration.exportData.maxNumberOfThreads}"
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:372)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
> 	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
> 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
> 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
> 	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
> 	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
> 	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:171)
> 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
> 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
> 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1099)
> 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:989)
> 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4931)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5241)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'cross.configuration.exportData.maxNumberOfThreads' in value "${cross.configuration.exportData.maxNumberOfThreads}"
> 	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
> 	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
> 	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:236)
> 	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
> 	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:172)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:831)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1086)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
> 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
> 	... 29 more

</p>
</details>

**Comment by alexctinpirtea** [comment]
In one of the latest build of the user interface library (web_ui-2.3-SNAPSHOT), a new component bean - **ExFormatEditorBuilder** - has been created inside **cz.sykora.cross.app.admin.builder** package.
In this class, an Integer property is defined as follows:

```
@Value("${cross.configuration.exportData.maxNumberOfThreads}")
private Integer maxNumberOfExportThreads;
```

It is mandatory to include and initialize this property in the base deploy.properties, otherwise java will raise an exception (see full stacktrace in main post).
This issue has been resolved in commit https://github.com/cross-logis/netbuilder/commit/c1c590c4d0bad1d45b1b016cea256b804025be9a (see line 121 for more details).
